---
#CONFIG VERSION
#DO NOT CHANGE THIS VALUE
version: 3

#ID of the relic. (Item given to player)
relic-id: 399

#Language
language: "fr"

#List of Block IDs that relics can be found with.
block-ids:
  - 3
  - 4
  - 12
  - 13
  
#List of Worlds where it apply [Array]
worlds: ["*"]

#Prevent placing block listed here to earn relic
prevent-placing: false

#Choose if the message is shown when a user finds a relic
found-message-enabled: true
#How the message is received. Options: title, tip or message
message-type: "title"
#Choose if particles shown when a player finds/opens a relic
particles-enabled: true

#Rarity of Relic. Do not change this!
common:
  #Chance in %
  chance: 5
  #List of commands. Use {player} for the player.
  #A command will be chosen at random from this list.
  commands:
    - "give {player} dirt 5"
    - "give {player} stone 10"

rare:
  chance: 3
  commands:
    - "give {player} dirt 10"
    - "give {player} stone 25"

epic:
  chance: 2
  commands:
    - "give {player} dirt 25"
    - "give {player} stone 50"

legendary:
  chance: 1
  commands:
    - "give {player} dirt 50"
    - "give {player} stone 64"
...